### ISSUE TITLE
windows_exporter_options does not affect the install

### ISSUE THREAD

**Issue by brandonmcclure** [DanielWeeber/ansible-role-windows_exporter#1]
When you specify the windows_exporter_options parameter when using this role the installer does not respect it/change the installation. 

## Desired state
specifying the role in a playbook like: 
```
- role: windows_exporter
      windows_exporter_version: '0.18.1'
      windows_exporter_options: 'ENABLED_COLLECTORS=cpu,cs,logical_disk,memory,net,os,textfile,iis TEXTFILE_DIR=D:\metrics'
```

results in a installation that has the specific collectors enables, and the textfile directory set to the user specified location. 
The readme would need to be updated to specify that you should use the MSI parameters as defined in the prometheus windows_exporter documentation here: https://github.com/prometheus-community/windows_exporter#installation

**Comment by DanielWeeber** [comment]
Nice catch. Thank you.
