### ISSUE TITLE
Control the service start_mode

### ISSUE THREAD

**Issue by brandonmcclure** [DanielWeeber/ansible-role-windows_exporter#3]
Currently when you change the `windows_exporter_state` default variable, there is no change on the target machine. 
Also, the service gets created with an `Automatic` start, but I have issues with it not starting after a system reboots. I want to be able to control the start_mode as well.

The way that I implemented this, is I removed the `windows_exporter_enabled` variable, and use the existing `windows_exporter_state` and a new `windows_exporter_start_mode` variable that are used to directly control the [win_service](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_service_module.html) task. I added a conditional check for the win_uri task, because if I disabled my service through these variables, then I would not want to check for the web service, becuase I expect it to not be running.

**Comment by DanielWeeber** [comment]
Merged. Thank you.
