### ISSUE TITLE
assert failed

### ISSUE THREAD

**Issue by zhan9san** [DanielWeeber/ansible-role-windows_exporter#5]
Thank you for creating this great project.

By default, `windows_exporter_state` is `started` and `windows_exporter_start_mode` is `delayed`.

So the assertion will always fail. What is the assertion for?

`windows_exporter_state != 'started' and windows_exporter_start_mode != 'disabled'`

https://github.com/DanielWeeber/ansible-role-windows_exporter/pull/4/files#diff-3d0ff1709ca48add100327bb2a468e6c508fb92a159c64c4f99ad1df89d9bddeR2-R6

Error message:

```txt
    "assertion": "windows_exporter_state != 'started' and windows_exporter_start_mode != 'disabled'",
    "changed": false,
    "evaluated_to": false,
    "msg": "You cannot manage the service with the windows_exporter_state and windows_exporter_start_mode settings"
```

**Comment by DanielWeeber** [comment]
Would you mind trying again after pulling new version? Just changed the assertion and a few other things a bit.

**Comment by zhan9san** [comment]
Thanks. I'll try it later

**Comment by zhan9san** [comment]
It works like a charm. Thank you @DanielWeeber
