### ISSUE TITLE
Optional firewall config

### ISSUE THREAD

**Issue by zhan9san** [DanielWeeber/ansible-role-windows_exporter#6]
Would it be possible to add a new confirmation item making firewall task optional?

In my case, firewall is off, and there is no need to execute firewall task here.

**Comment by DanielWeeber** [comment]
Does it fail when the firewall is turned off?

**Comment by zhan9san** [comment]
Thanks for your attention.

I can verify it tomorrow or next Monday.

But it will be great if we can execute firewall task on demand.

e.g.
execute it by default and   doesn't if there is an explicit configuration item.

**Comment by DanielWeeber** [comment]
Does not seem to fail for me when the firewall is disabled.
As this is not failing and still idempotent there does not need to be a check if the firewall is turned on or off.

**Comment by zhan9san** [comment]
Thanks for your confirmation. I verified it as well, and it doesn't fail.

> As this is not failing and still idempotent there does not need to be a check if the firewall is turned on or off.

If we have a configuration like `windows_exporter_firewall: off`, we can skip this task, `Firewall rule to allow Prometheus to scrape on port 9182 TCP`.

There is no need to touch firewall on target nodes when firewall is off.

Do you have any concern?

**Comment by DanielWeeber** [comment]
yeah, I dont get it why it shouldn't be added even though the firewall is not activated.
it does not hurt.
if you decide to enable it sometime in the future the rule is already in place.

whats so bad about adding it although deactivated?

**Comment by zhan9san** [comment]
Thanks for your feedback.

If the firewall is not activated, no matter executing the firewall task or not, the service is always available. So I think it's not necessary to execute a task which cannot influence the result.

> if you decide to enable it sometime in the future the rule is already in place.

It someone doesn't enable it, the already in-place rules may be useless. But we still execute it.

I'm sorry if my advice offended you ─ I meant it for the best.

**Comment by DanielWeeber** [comment]
no worries! i'm open for any discussion :)
a condition for the task would be fine for me, but no configuration switch should be added for this.

do you know any specific command/condition we could check there? an easy true/false command if the firewall is enabled?

**Comment by zhan9san** [comment]
Glad to hear that.

We don't need to check the firewall on target enabled or not.

Instead, I agree with you that adding a condition on firewall task is okay.

The configuration name can be something like windows_exporter_firewall

**Comment by DanielWeeber** [comment]
Would you mind testing https://github.com/DanielWeeber/ansible-role-windows_exporter/pull/7?
should skip the task automatically now

**Comment by zhan9san** [comment]
The firewall task is skipped.

Could we release a new version?

```shell
TASK [ansible-role-windows_exporter : find firewall status] ***********************************************************************************************************************************************************************
task path: /Users/jackzhang/.ansible/roles/ansible-role-windows_exporter/tasks/main.yml:41
redirecting (type: modules) ansible.builtin.win_shell to ansible.windows.win_shell
ok: [xxx] => {"changed": false, "cmd": "Get-NetFirewallProfile | Where-Object {$_.Enabled -eq $true} | fl Enabled", "delta": "0:00:12.398691", "end": "2022-06-06 07:03:39.156749", "rc": 0, "start": "2022-06-06 07:03:26.758058", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

TASK [ansible-role-windows_exporter : Firewall rule to allow Prometheus to scrape on port 9182 TCP] *******************************************************************************************************************************
task path: /Users/jackzhang/.ansible/roles/ansible-role-windows_exporter/tasks/main.yml:46
skipping: [xxx] => {"changed": false, "skip_reason": "Conditional result was False"}
```

**Comment by DanielWeeber** [comment]
Thank you for testing. I just merged the pull request, the new release is just right now being built and uploaded.
